version: "3"

services:
  website:
    image: justapenguin.ca
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PASSWORD: ${DB_PASSWORD}
      NODE_ENV: production
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    ports:
      - 5009:3000
    networks:
      database: {}

networks:
  database:
    external: true
